on: [push]

jobs:
  docker_job:
    runs-on: ubuntu-latest
    name: Optimistic
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fastapi-app -f Backend/Dockerfile .

      - name: Push container image
        run: docker push ghcr.io/ludorif/optimistic:latest


